from ..approval_contract import APPROVAL_DECISION_APPROVE, APPROVAL_DECISION_REJECT
from ..tools import API_CONTEXT, ToolSpec

ACTION_SPECS = [
    ToolSpec(
        name="final.answer",
        capability_class="conversation",
        execution_contexts=("turn", "actuator", "react", "workflow_step"),
        description="""Return a final user-facing message.""",
        input_schema={
            "type": "object",
            "properties": {"message": {"type": "string"}},
            "required": ["message"],
        },
        output_schema={"type": "object", "properties": {"message": {"type": "string"}}},
        facts_only=True,
        mutates=False,
        permission="read",
        source="action",
    ),
    ToolSpec(
        name="ask.user",
        capability_class="conversation",
        execution_contexts=("turn", "actuator", "workflow_step"),
        description="""Ask the user a question to clarify requirements or present multiple choices for a decision, suitable for human-in-the-loop workflows.""",
        input_schema={
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "description": "The question or context to present to the user.",
                },
                "options": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Optional list of explicit choices for the user to pick from.",
                },
            },
            "required": ["message"],
        },
        output_schema={"type": "object", "properties": {"message": {"type": "string"}}},
        facts_only=True,
        mutates=False,
        permission="read",
        source="action",
    ),
    ToolSpec(
        name="delegate.spawn",
        capability_class="delegation",
        execution_contexts=("turn", "workflow_step"),
        description="""Create a narrowly-scoped delegation run whose task executes in Navi's governed local execution context.""",
        input_schema={
            "type": "object",
            "properties": {
                "objective": {"type": "string", "description": "The main goal of this delegation."},
                "context": {
                    "type": "string",
                    "description": "Relevant background information, gathered facts, and constraints.",
                },
                "plan": {
                    "type": "string",
                    "description": "Concise execution plan and evidence scope for the delegation run.",
                },
                "success_criteria": {
                    "type": "string",
                    "description": "How to verify that the delegation succeeded.",
                },
                "workspace": {
                    "type": "string",
                    "description": "Optional absolute path to run the task in. Defaults to the current workspace.",
                },
            },
            "required": ["objective", "context", "plan", "success_criteria"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "status": {"type": "string"},
                "goal_id": {"type": "string"},
                "workspace": {"type": "string"},
                "requires_user_approval": {"type": "boolean"},
                "deduplicated": {"type": "boolean"},
                "surface_message": {"type": "string"},
                "approval": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
    ),
    ToolSpec(
        name="delegate.prepare",
        capability_class="delegation",
        execution_contexts=("turn", "workflow_step"),
        description="""Prepare an existing delegation run and return preparation facts.""",
        input_schema={
            "type": "object",
            "properties": {"run_id": {"type": "string"}},
            "required": ["run_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "status": {"type": "string"},
                "plan_summary": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
    ),
    ToolSpec(
        name="approval.request",
        capability_class="approval",
        execution_contexts=("turn", "workflow_step"),
        description="""Create an approval request for a delegation run.""",
        input_schema={
            "type": "object",
            "properties": {"run_id": {"type": "string"}},
            "required": ["run_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "status": {"type": "string"},
                "approval": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
        governance_exempt=True,
    ),
    ToolSpec(
        name="delegate.run",
        capability_class="delegation",
        execution_contexts=("turn", "workflow_step"),
        description="""Queue a delegation run that has an execution grant.""",
        input_schema={
            "type": "object",
            "properties": {"run_id": {"type": "string"}},
            "required": ["run_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "status": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="watch.create",
        capability_class="watch",
        execution_contexts=("turn", "workflow_step"),
        description="""Create a scheduled watch record.""",
        input_schema={
            "type": "object",
            "properties": {
                "prompt": {"type": "string"},
                "cron": {"type": "string"},
                "run_at": {"type": "number", "description": "Unix timestamp indicating when to run"},
                "kind": {"type": "string", "enum": ["once", "recurring"]},
            },
            "required": ["prompt"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "watch_id": {"type": "string"},
                "cron": {"type": "string"},
                "kind": {"type": "string"},
                "prompt": {"type": "string"},
                "completion_evidence": {"type": "boolean"},
                "next_run_at": {"type": "number"},
                "next_run_text": {"type": "string"},
                "surface_message": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
    ),
    ToolSpec(
        name="delegate.delete",
        capability_class="delegation",
        execution_contexts=("turn", "workflow_step"),
        description="""Delete delegation run records by id or by explicit cleanup scope.""",
        input_schema={
            "type": "object",
            "properties": {
                "run_id": {"type": "string", "description": "Target a single run by id."},
                "status": {
                    "type": "string",
                    "description": "Bulk cleanup filter. Status-only filters are rejected: include `source` or `kind` to scope the deletion.",
                },
                "source": {
                    "type": "string",
                    "description": "Bulk cleanup scope: delete runs from this source.",
                },
                "kind": {
                    "type": "string",
                    "description": "Bulk cleanup scope: delete runs of this kind.",
                },
                "limit": {"type": "integer"},
                "reason": {"type": "string"},
            },
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "completion_evidence": {"type": "boolean"},
                "run_id": {"type": "string"},
                "deleted": {"type": "boolean"},
                "deleted_count": {"type": "integer"},
                "remaining_count": {"type": "integer"},
                "cleanup_complete": {"type": "boolean"},
                "deleted_runs": {"type": "array", "items": {"type": "object"}},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="delegate.list",
        capability_class="delegation",
        execution_contexts=("turn", "workflow_step"),
        description="""Return delegation runs and recurring watches for the current caller's context as delegation-management facts. Results are scoped to the caller's surface; tasks created on other channels are not listed.""",
        input_schema={
            "type": "object",
            "properties": {"limit": {"type": "integer", "default": 20}},
        },
        output_schema={
            "type": "object",
            "properties": {
                "runs": {"type": "array", "items": {"type": "object"}},
                "watches": {"type": "array", "items": {"type": "object"}},
                "run_status_counts": {"type": "object"},
                "returned_run_count": {"type": "integer"},
                "run_limit": {"type": "integer"},
            },
        },
        facts_only=True,
        mutates=False,
        permission="read",
        source="action",
    ),
    ToolSpec(
        name="watch.delete",
        capability_class="watch.delete",
        execution_contexts=("turn", "workflow_step"),
        description="""Permanently delete a watch or task (recurring or one-time) by watch id.""",
        input_schema={
            "type": "object",
            "properties": {
                "watch_id": {"type": "string"},
                "reason": {"type": "string"},
            },
            "required": ["watch_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "completion_evidence": {"type": "boolean"},
                "watch_id": {"type": "string"},
                "deleted": {"type": "boolean"},
                "cron": {"type": "string"},
                "prompt": {"type": "string"},
                "surface_message": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="approval.resolve",
        capability_class="approval",
        execution_contexts=(API_CONTEXT,),
        description="""Resolve a pending approval by explicit code, current run id, or an explicit visible approval selection.""",
        input_schema={
            "type": "object",
            "properties": {
                "decision": {
                    "type": "string",
                    "enum": [APPROVAL_DECISION_APPROVE, APPROVAL_DECISION_REJECT],
                },
                "code": {"type": "string"},
                "run_id": {"type": "string"},
                "batch_id": {"type": "string"},
                "approval_evidence": {
                    "type": "string",
                    "description": "Exact substring from the current user input recorded as approval evidence for non-code selections.",
                },
                "selection": {
                    "type": "string",
                    "enum": [
                        "explicit_code",
                        "current_run",
                        "batch_id",
                        "latest_visible_batch",
                        "all_visible",
                    ],
                },
            },
            "required": ["decision"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "approval_status": {"type": "string"},
                "run_status": {"type": "string"},
                "completion_evidence": {"type": "boolean"},
                "resolved_count": {"type": "integer"},
                "failed_count": {"type": "integer"},
                "surface_message": {"type": "string"},
                "resolved": {"type": "array", "items": {"type": "object"}},
                "failures": {"type": "array", "items": {"type": "object"}},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        governance_exempt=True,
    ),
    ToolSpec(
        name="delegate.retry",
        capability_class="delegation",
        execution_contexts=("turn", "workflow_step"),
        description="""Execute one retry attempt for a delegation run.""",
        input_schema={
            "type": "object",
            "properties": {"run_id": {"type": "string"}, "follow_up_prompt": {"type": "string"}},
            "required": ["run_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "status": {"type": "string"},
                "result_summary": {"type": "string"},
                "error": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="workflow.propose",
        capability_class="workflow",
        execution_contexts=("turn",),
        description="""Propose a governed dynamic workflow with declared subagent steps and verification strategy.""",
        input_schema={
            "type": "object",
            "properties": {
                "objective": {"type": "string"},
                "permission_ceiling": {"type": "string"},
                "max_concurrency": {"type": "integer"},
                "total_subagent_limit": {"type": "integer"},
                "risk_class": {"type": "string"},
                "estimated_cost": {"type": "string"},
                "stop_condition": {"type": "string"},
                "verification_strategy": {"type": "string"},
                "plan": {"type": "object"},
                "steps": {"type": "array", "items": {"type": "object"}},
            },
            "required": ["objective"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "workflow_id": {"type": "string"},
                "status": {"type": "string"},
                "confirmation_required": {"type": "boolean"},
                "permission_ceiling": {"type": "string"},
                "max_concurrency": {"type": "integer"},
                "total_subagent_limit": {"type": "integer"},
                "step_count": {"type": "integer"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
    ),
    ToolSpec(
        name="workflow.approve",
        capability_class="workflow",
        execution_contexts=("turn",),
        description="""Approve or reject a proposed dynamic workflow before it can run.""",
        input_schema={
            "type": "object",
            "properties": {
                "workflow_id": {"type": "string"},
                "decision": {
                    "type": "string",
                    "enum": [APPROVAL_DECISION_APPROVE, APPROVAL_DECISION_REJECT],
                },
            },
            "required": ["workflow_id", "decision"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "workflow_id": {"type": "string"},
                "status": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="workflow.run",
        capability_class="workflow",
        execution_contexts=("turn",),
        description="""Run the next bounded batch of an approved dynamic workflow as model-owned step loops constrained by each step's declared tool scope. When all steps are complete, the verifier runs automatically and the workflow transitions to verified or blocked. Set resume=true to resume an interrupted workflow.""",
        input_schema={
            "type": "object",
            "properties": {
                "workflow_id": {"type": "string"},
                "resume": {"type": "boolean", "default": False},
            },
            "required": ["workflow_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "workflow_id": {"type": "string"},
                "status": {"type": "string"},
                "completed_count": {"type": "integer"},
                "failed_count": {"type": "integer"},
                "pending_count": {"type": "integer"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="workflow.status",
        capability_class="workflow",
        execution_contexts=("turn",),
        description="""Inspect one dynamic workflow, including step state, evidence, and lifecycle events.""",
        input_schema={
            "type": "object",
            "properties": {"workflow_id": {"type": "string"}},
            "required": ["workflow_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "workflow": {"type": "object"},
                "steps": {"type": "array", "items": {"type": "object"}},
                "events": {"type": "array", "items": {"type": "object"}},
                "step_count": {"type": "integer"},
                "pending_count": {"type": "integer"},
                "completed_count": {"type": "integer"},
                "failed_count": {"type": "integer"},
            },
        },
        facts_only=True,
        mutates=False,
        permission="read",
        source="action",
    ),
    ToolSpec(
        name="session.request_elevation",
        capability_class="session",
        execution_contexts=("turn", "workflow_step"),
        description="""Create a temporary session permission elevation request record.""",
        input_schema={
            "type": "object",
            "properties": {
                "target_permission": {"type": "string", "enum": ["prepare", "write", "execute"]},
                "reason": {"type": "string"},
            },
            "required": ["target_permission"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "status": {"type": "string"},
                "target_permission": {"type": "string"},
                "reason": {"type": "string"},
                "approval": {
                    "type": "object",
                    "properties": {
                        "action": {"type": "string"},
                        "code": {"type": "string"},
                        "expires_at": {"type": "number"},
                    },
                },
                "run_id": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="read",
        source="action",
    ),
    ToolSpec(
        name="session.create",
        capability_class="session",
        execution_contexts=("api",),
        description="""Create a conversation session, optionally binding an alias.""",
        input_schema={"type": "object", "properties": {"alias": {"type": "string"}}},
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "session_id": {"type": "string"},
                "alias": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
    ),
    ToolSpec(
        name="memory.add",
        capability_class="memory",
        execution_contexts=("api",),
        description="""Add one typed durable memory item through the capability boundary.""",
        input_schema={
            "type": "object",
            "properties": {
                "type": {"type": "string"},
                "content": {"type": "string"},
                "scope": {"type": "string"},
                "source": {"type": "string"},
                "status": {"type": "string"},
                "confidence": {"type": "number"},
                "reason": {"type": "string"},
                "provenance": {"type": "string"},
                "metadata": {"type": "object"},
            },
            "required": ["type", "content", "reason", "provenance"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "item": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="trace.evaluate",
        capability_class="trace",
        execution_contexts=("api",),
        description="""Evaluate one trace and persist the trace evaluation record.""",
        input_schema={
            "type": "object",
            "properties": {"trace_id": {"type": "string"}},
            "required": ["trace_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "evaluation": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="evolution.propose",
        capability_class="evolution",
        execution_contexts=("api",),
        description="""Create a reviewable evolution proposal through the capability boundary.""",
        input_schema={
            "type": "object",
            "properties": {
                "target_type": {"type": "string"},
                "target_id": {"type": "string"},
                "reason": {"type": "string"},
                "expected_benefit": {"type": "string"},
                "risk": {"type": "string"},
                "before": {"type": "string"},
                "after": {"type": "string"},
                "rollback_plan": {"type": "string"},
                "required_approval_level": {"type": "string"},
                "evidence": {"type": "string"},
                "source_run_id": {"type": "string"},
                "eval_cases": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["target_type", "target_id", "reason"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "proposal": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
    ),
    ToolSpec(
        name="evolution.record_evaluation",
        capability_class="evolution",
        execution_contexts=("api",),
        description="""Attach evaluation evidence to an evolution proposal.""",
        input_schema={
            "type": "object",
            "properties": {
                "proposal_id": {"type": "string"},
                "evaluation_result": {"type": "string"},
            },
            "required": ["proposal_id", "evaluation_result"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "proposal": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="evolution.apply",
        capability_class="evolution",
        execution_contexts=("api",),
        description="""Apply an approved evolution proposal.""",
        input_schema={
            "type": "object",
            "properties": {"proposal_id": {"type": "string"}},
            "required": ["proposal_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "event": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="evolution.rollback",
        capability_class="evolution",
        execution_contexts=("api",),
        description="""Roll back a reversible evolution event.""",
        input_schema={
            "type": "object",
            "properties": {"event_id": {"type": "string"}},
            "required": ["event_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "event": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
]
