from ..approval_contract import APPROVAL_DECISION_APPROVE, APPROVAL_DECISION_REJECT
from ..tools import API_CONTEXT, CONTROL_PLANE_CONTEXT, ToolSpec

ACTION_SPECS = [
    ToolSpec(
        name="respond",
        capability_class="conversation",
        execution_contexts=("turn", "actuator", CONTROL_PLANE_CONTEXT),
        description=(
            "Send a terminal user-facing message. This action never pauses the "
            "loop or waits for input. message is the only user-visible body. "
            "private_evidence is structured checker/trace evidence and is never "
            "delivered to the user. Options are non-blocking presentation facts."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "description": "The message to present to the user.",
                },
                "options": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Optional list of explicit choices for the user to pick from.",
                },
                "private_evidence": {
                    "type": "object",
                    "description": (
                        "Structured non-user-visible evidence for checker/trace "
                        "validation, such as smoke markers or audit facts."
                    ),
                },
            },
            "required": ["message"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "message": {"type": "string"},
                "options": {"type": "array", "items": {"type": "string"}},
                "private_evidence": {"type": "object"},
                "private_evidence_provenance": {"type": "string"},
            },
        },
        facts_only=False,
        mutates=False,
        permission="read",
        source="action",
    ),
    ToolSpec(
        name="ask.user",
        capability_class="conversation",
        execution_contexts=("turn", "actuator", CONTROL_PLANE_CONTEXT),
        description="""Ask the user a blocking question and pause the loop until the user responds. This action yields control to the user.""",
        input_schema={
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "description": "The question to present to the user.",
                },
                "options": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Optional explicit choices for the user to pick from.",
                },
            },
            "required": ["message"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "message": {"type": "string"},
                "options": {"type": "array", "items": {"type": "string"}},
            },
        },
        facts_only=False,
        mutates=False,
        permission="read",
        source="action",
    ),
    ToolSpec(
        name="account.usage",
        capability_class="account",
        execution_contexts=("turn", API_CONTEXT),
        description=(
            "Read account quota, usage, credit, or rate-limit windows for a configured "
            "inference provider through provider account APIs and local auth state. "
            "Returns typed facts when live usage is available and typed "
            "unavailable_reason/auth facts when "
            "the provider or network cannot supply account usage."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "provider": {
                    "type": "string",
                    "description": "Provider slug, such as openai-codex or codex.",
                },
                "timeout_seconds": {
                    "type": "number",
                    "description": "Network timeout in seconds, clamped by the capability.",
                },
            },
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "provider": {"type": "string"},
                "source": {"type": "string"},
                "fetched_at": {"type": "string"},
                "available": {"type": "boolean"},
                "plan": {"type": "string"},
                "auth_status": {"type": "string"},
                "windows": {"type": "array", "items": {"type": "object"}},
                "details": {"type": "array", "items": {"type": "string"}},
                "unavailable_reason": {"type": "string"},
            },
            "required": [
                "entity_type",
                "entity_id",
                "state_transition",
                "turn_scope",
                "provider",
                "available",
            ],
        },
        facts_only=True,
        mutates=False,
        permission="network",
        source="action",
    ),
    ToolSpec(
        name="agent.control",
        capability_class="agent",
        risk_class="medium",
        sensitive_contexts=("task_control",),
        confirmation_required=False,
        risk_reason_code="capability_safeguard_agent_control",
        execution_contexts=("turn", API_CONTEXT),
        description=(
            "Manage depth-1 child Goals only through one operation-selected lifecycle "
            "surface. Records outside the specified parent/child scope are not returned "
            "or mutated. Read child operations are "
            "list, state, and collect; mutating child operations are spawn, message, "
            "and cancel. The state operation requires child_goal_id. Top-level goals, "
            "scheduled goals, pending approval goals, approvals, and general task "
            "cleanup are outside this capability's authority."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "operation": {
                    "type": "string",
                    "enum": ["spawn", "list", "state", "message", "cancel", "collect"],
                },
                "parent_goal_id": {"type": "string"},
                "child_goal_id": {"type": "string"},
                "objective": {"type": "string"},
                "acceptance_criteria": {"type": "array", "items": {"type": "string"}},
                "context_facts": {"type": "object"},
                "allowed_capabilities": {"type": "array", "items": {"type": "string"}},
                "message": {"type": "string"},
                "facts": {"type": "object"},
                "reason": {"type": "string"},
                "limit": {"type": "integer", "minimum": 1},
                "timeout_seconds": {"type": "integer", "minimum": 1},
                "token_budget": {"type": "integer", "minimum": 1},
                "call_budget": {"type": "integer", "minimum": 1},
                "cost_budget": {"type": "number", "minimum": 0},
                "qps_limit": {"type": "integer", "minimum": 1},
            },
            "required": ["operation"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "parent_goal_id": {"type": "string"},
                "child_goal_id": {"type": "string"},
                "children": {"type": "array", "items": {"type": "object"}},
                "child": {"type": "object"},
                "reports": {"type": "array", "items": {"type": "object"}},
                "latest_report": {"type": "object"},
                "completion_evidence": {"type": "boolean"},
                "run_id": {"type": "string"},
                "loop_run_id": {"type": "string"},
                "phase": {"type": "string"},
                "task_status": {"type": "string"},
                "execution_mode": {"type": "string"},
                "permission_ceiling": {"type": "string"},
                "allowed_capabilities": {"type": "array", "items": {"type": "string"}},
                "budget_policy": {"type": "object"},
                "timeout_seconds": {"type": "integer"},
                "active_children": {"type": "integer"},
                "max_active_children": {"type": "integer"},
                "message_id": {"type": "string"},
            },
            "required": ["entity_type", "entity_id", "state_transition", "turn_scope"],
        },
        facts_only=True,
        deterministic_completion_authority=True,
        mutates=True,
        permission="read",
        permission_policy="agent_operation",
        risk_policy="agent_operation",
        delegation_allowed=False,
        source="action",
    ),
    ToolSpec(
        name="agent.report",
        capability_class="agent",
        risk_class="medium",
        sensitive_contexts=("task_control",),
        confirmation_required=False,
        risk_reason_code="capability_safeguard_agent_report",
        execution_contexts=("turn",),
        description=(
            "Terminal child-only protocol action that reports findings and evidence "
            "to the parent Goal; it never sends a user-facing response."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "summary": {"type": "string"},
                "findings": {"type": "array", "items": {"type": "object"}},
                "evidence_refs": {"type": "array", "items": {"type": "string"}},
                "artifacts": {"type": "array", "items": {"type": "string"}},
                "unresolved": {"type": "array", "items": {"type": "string"}},
                "needs_parent_input": {"type": "boolean"},
            },
            "required": ["summary"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "parent_goal_id": {"type": "string"},
                "child_goal_id": {"type": "string"},
                "report_id": {"type": "string"},
                "report": {"type": "object"},
            },
            "required": [
                "entity_type",
                "entity_id",
                "state_transition",
                "turn_scope",
                "parent_goal_id",
                "child_goal_id",
                "report_id",
                "report",
            ],
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        delegation_allowed=False,
        source="action",
    ),
    ToolSpec(
        name="goal.open",
        capability_class="goal",
        risk_class="medium",
        sensitive_contexts=("task_control",),
        confirmation_required=False,
        risk_reason_code="capability_safeguard_goal_open",
        runtime_policy="when_auto_start",
        execution_contexts=("turn", API_CONTEXT),
        description=(
            "Create a durable, foreground, manual, or scheduled Goal/LoopRun "
            "within the current capability and permission envelope."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "objective": {"type": "string"},
                "workspace": {"type": "string"},
                "loop_kind": {
                    "type": "string",
                    "enum": ["turn", "control", "durable_goal", "scheduled"],
                },
                "cron_schedule": {
                    "type": "string",
                    "description": (
                        "Required when loop_kind is scheduled; a five-field cron "
                        "expression interpreted in the service's local timezone."
                    ),
                },
                "parent_goal_id": {"type": "string"},
                "scope": {"type": "array", "items": {"type": "string"}},
                "constraints": {"type": "array", "items": {"type": "string"}},
                "acceptance_criteria": {"type": "array", "items": {"type": "string"}},
                "permission_ceiling": {"type": "string"},
                "allowed_capabilities": {"type": "array", "items": {"type": "string"}},
                "verification_command": {"type": "string"},
                "timeout_seconds": {"type": "integer"},
                "token_budget": {"type": "integer", "minimum": 0},
                "call_budget": {"type": "integer", "minimum": 0},
                "cost_budget": {"type": "number", "minimum": 0},
                "qps_limit": {"type": "integer", "minimum": 0},
                "max_concurrent": {"type": "integer", "minimum": 1},
                "auto_start": {"type": "boolean"},
                "allow_duplicate_schedule": {"type": "boolean"},
            },
            "required": ["objective"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "goal_id": {"type": "string"},
                "run_id": {"type": "string"},
                "loop_spec_id": {"type": "string"},
                "loop_run_id": {"type": "string"},
                "route": {"type": "string"},
                "loop_kind": {"type": "string"},
                "execution_mode": {"type": "string"},
                "cron_schedule": {"type": "string"},
                "next_run_at": {"type": "number"},
                "registration_evidence": {"type": "boolean"},
                "budget_policy": {"type": "object"},
                "phase": {"type": "string"},
                "governance": {"type": "string"},
                "acceptance": {"type": "string"},
                "resolution": {"type": "string"},
                "loop_node": {"type": "string"},
                "loop_terminal_state": {"type": "string"},
                "completion_evidence": {"type": "boolean"},
                "state_graph_result": {"type": "object"},
                "responded_message": {"type": "string"},
                "responded_action": {"type": "string"},
                "action": {"type": "string"},
                "connector_delivery": {"type": "object"},
                "pending_approval": {"type": "object"},
            },
        },
        facts_only=True,
        deterministic_completion_authority=True,
        mutates=True,
        permission="prepare",
        source="action",
    ),
    ToolSpec(
        name="goal.update",
        capability_class="goal",
        risk_class="medium",
        sensitive_contexts=("task_control",),
        confirmation_required=False,
        risk_reason_code="capability_safeguard_goal_update",
        runtime_policy="required",
        execution_contexts=("turn", API_CONTEXT),
        description=(
            "Update mutable fields on one existing scheduled recurring Goal "
            "template selected by goal_id."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "goal_id": {"type": "string"},
                "objective": {"type": "string"},
                "cron_schedule": {
                    "type": "string",
                    "description": (
                        "Optional replacement five-field cron expression "
                        "interpreted in the service's local timezone."
                    ),
                },
                "scope": {"type": "array", "items": {"type": "string"}},
                "constraints": {"type": "array", "items": {"type": "string"}},
                "acceptance_criteria": {"type": "array", "items": {"type": "string"}},
                "permission_ceiling": {"type": "string"},
                "allowed_capabilities": {"type": "array", "items": {"type": "string"}},
                "verification_command": {"type": "string"},
                "timeout_seconds": {"type": "integer"},
                "token_budget": {"type": "integer", "minimum": 0},
                "call_budget": {"type": "integer", "minimum": 0},
                "cost_budget": {"type": "number", "minimum": 0},
                "qps_limit": {"type": "integer", "minimum": 0},
                "max_concurrent": {"type": "integer", "minimum": 1},
                "allow_duplicate_schedule": {"type": "boolean"},
            },
            "required": ["goal_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "goal_id": {"type": "string"},
                "run_id": {"type": "string"},
                "loop_spec_id": {"type": "string"},
                "loop_run_id": {"type": "string"},
                "route": {"type": "string"},
                "loop_kind": {"type": "string"},
                "execution_mode": {"type": "string"},
                "cron_schedule": {"type": "string"},
                "next_run_at": {"type": "number"},
                "registration_evidence": {"type": "boolean"},
                "budget_policy": {"type": "object"},
                "phase": {"type": "string"},
                "governance": {"type": "string"},
                "acceptance": {"type": "string"},
                "resolution": {"type": "string"},
                "loop_node": {"type": "string"},
                "loop_terminal_state": {"type": "string"},
                "completion_evidence": {"type": "boolean"},
                "state_graph_result": {"type": "object"},
                "responded_message": {"type": "string"},
                "responded_action": {"type": "string"},
                "action": {"type": "string"},
                "connector_delivery": {"type": "object"},
                "pending_approval": {"type": "object"},
            },
        },
        facts_only=True,
        deterministic_completion_authority=True,
        mutates=True,
        permission="prepare",
        source="action",
    ),
    ToolSpec(
        name="goal.resume",
        capability_class="goal",
        risk_class="high",
        sensitive_contexts=("task_control", "local_state"),
        confirmation_required=True,
        risk_reason_code="capability_safeguard_goal_resume",
        approval_policy="explicit_control",
        runtime_policy="required",
        execution_contexts=("turn", API_CONTEXT),
        description="""Resume a durable Goal/LoopRun from its persisted checkpoint through the LoopControlService.""",
        input_schema={
            "type": "object",
            "properties": {
                "goal_id": {"type": "string"},
                "loop_run_id": {"type": "string"},
                "workspace": {"type": "string"},
            },
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "goal_id": {"type": "string"},
                "run_id": {"type": "string"},
                "loop_spec_id": {"type": "string"},
                "loop_run_id": {"type": "string"},
                "route": {"type": "string"},
                "loop_kind": {"type": "string"},
                "execution_mode": {"type": "string"},
                "cron_schedule": {"type": "string"},
                "next_run_at": {"type": "number"},
                "registration_evidence": {"type": "boolean"},
                "budget_policy": {"type": "object"},
                "phase": {"type": "string"},
                "governance": {"type": "string"},
                "acceptance": {"type": "string"},
                "resolution": {"type": "string"},
                "loop_node": {"type": "string"},
                "loop_terminal_state": {"type": "string"},
                "completion_evidence": {"type": "boolean"},
                "state_graph_result": {"type": "object"},
                "responded_message": {"type": "string"},
                "responded_action": {"type": "string"},
                "action": {"type": "string"},
                "connector_delivery": {"type": "object"},
                "pending_approval": {"type": "object"},
            },
        },
        facts_only=True,
        deterministic_completion_authority=True,
        mutates=True,
        permission="prepare",
        source="action",
    ),
    ToolSpec(
        name="goal.cancel",
        capability_class="goal",
        risk_class="high",
        sensitive_contexts=("task_control",),
        confirmation_required=True,
        risk_reason_code="capability_safeguard_goal_cancel",
        approval_policy="explicit_control",
        execution_contexts=("turn", API_CONTEXT),
        description="""Cancel durable Goal lifecycle records and verify the final state. goal_id selects one goal, loop_run_id selects one loop, and goal_ids selects an explicit batch within the caller scope.""",
        input_schema={
            "type": "object",
            "properties": {
                "goal_id": {"type": "string"},
                "goal_ids": {"type": "array", "items": {"type": "string"}},
                "loop_run_id": {"type": "string"},
                "reason": {"type": "string"},
            },
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "goal_id": {"type": "string"},
                "run_id": {"type": "string"},
                "loop_spec_id": {"type": "string"},
                "loop_run_id": {"type": "string"},
                "route": {"type": "string"},
                "loop_kind": {"type": "string"},
                "execution_mode": {"type": "string"},
                "cron_schedule": {"type": "string"},
                "next_run_at": {"type": "number"},
                "registration_evidence": {"type": "boolean"},
                "budget_policy": {"type": "object"},
                "phase": {"type": "string"},
                "governance": {"type": "string"},
                "acceptance": {"type": "string"},
                "resolution": {"type": "string"},
                "loop_node": {"type": "string"},
                "loop_terminal_state": {"type": "string"},
                "completion_evidence": {"type": "boolean"},
                "verified_goal": {"type": "object"},
                "verified_state": {"type": "object"},
                "verified_after": {"type": "object"},
                "state_graph_result": {"type": "object"},
                "verification_evidence": {"type": "boolean"},
                "selector": {"type": "object"},
                "requested_count": {"type": "integer"},
                "cancelled_count": {"type": "integer"},
                "failed_count": {"type": "integer"},
                "cancelled_goals": {"type": "array", "items": {"type": "object"}},
                "failed_goals": {"type": "array", "items": {"type": "object"}},
            },
        },
        facts_only=True,
        deterministic_completion_authority=True,
        mutates=True,
        permission="prepare",
        source="action",
    ),
    ToolSpec(
        name="goal.state",
        capability_class="goal",
        risk_class="medium",
        sensitive_contexts=("task_control",),
        confirmation_required=False,
        risk_reason_code="capability_safeguard_goal_state",
        execution_contexts=("turn", API_CONTEXT),
        description="""Read authoritative durable Goal and LoopRun state without mutating execution. An ID selects that exact goal or loop run. Without an ID, inbox returns one task-oriented view; narrower views select current foreground goals, scheduled recurring goals, goals waiting for approval, or task history.""",
        input_schema={
            "type": "object",
            "properties": {
                "goal_id": {"type": "string"},
                "loop_run_id": {"type": "string"},
                "view": {
                    "type": "string",
                    "description": "inbox, current, scheduled, pending_approval, or history; defaults to current.",
                },
                "limit": {"type": "integer"},
            },
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "goal": {"type": "object"},
                "run": {"type": "object"},
                "loop_run": {"type": "object"},
                "loop_runs": {"type": "array", "items": {"type": "object"}},
                "active_loop_runs": {"type": "array", "items": {"type": "object"}},
                "active_goals": {"type": "array", "items": {"type": "object"}},
                "query_scope": {"type": "string"},
                "view": {"type": "string"},
                "authoritative_for": {"type": "string"},
                "matched_count": {"type": "integer"},
                "goal_counts": {"type": "object"},
                "goals": {"type": "array", "items": {"type": "object"}},
                "current_goals": {"type": "array", "items": {"type": "object"}},
                "scheduled_goals": {"type": "array", "items": {"type": "object"}},
                "pending_approval_goals": {"type": "array", "items": {"type": "object"}},
                "history_goals": {"type": "array", "items": {"type": "object"}},
            },
            "required": ["entity_type", "entity_id", "state_transition", "turn_scope"],
        },
        facts_only=True,
        mutates=False,
        permission="read",
        source="action",
    ),
    ToolSpec(
        name="approval.request",
        capability_class="approval",
        risk_class="medium",
        sensitive_contexts=("approval_control",),
        confirmation_required=False,
        risk_reason_code="capability_safeguard_approval_request",
        execution_contexts=("turn", API_CONTEXT),
        description="""Create a durable approval request for a run, execution grant, or specific sensitive capability call.""",
        input_schema={
            "type": "object",
            "properties": {
                "run_id": {"type": "string"},
                "action": {"type": "string"},
                "requested_tool": {"type": "string"},
                "requested_permission": {"type": "string"},
                "args": {"type": "object"},
                "args_json": {"type": "string"},
                "reason": {"type": "string"},
            },
            "required": ["run_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "status": {"type": "string"},
                "approval": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
        approval_policy="control_plane",
    ),
    ToolSpec(
        name="approval.resolve",
        capability_class="approval",
        risk_class="medium",
        sensitive_contexts=("approval_control",),
        confirmation_required=False,
        risk_reason_code="capability_safeguard_approval_resolve",
        execution_contexts=("turn", API_CONTEXT),
        description=(
            "Resolve one durable approval by code or run id, resume only the approval gate "
            "bound to that record, and return separate facts for the approval control action "
            "and the original task continuation. approval_control_completion_evidence means "
            "the requested approve/reject decision was applied; completion_evidence describes "
            "whether the resumed original task reached its own objective. If continuation "
            "requires a distinct new approval, pending_approval identifies that next gate; do "
            "not resolve the same already-approved record again."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "decision": {
                    "type": "string",
                    "enum": [APPROVAL_DECISION_APPROVE, APPROVAL_DECISION_REJECT],
                },
                "code": {"type": "string"},
                "run_id": {"type": "string"},
            },
            "required": ["decision"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "decision": {"type": "string"},
                "code_present": {"type": "boolean"},
                "active_run_count": {"type": "integer"},
                "run_id": {"type": "string"},
                "approval_id": {"type": "string"},
                "action": {"type": "string"},
                "status": {"type": "string"},
                "state_transition": {"type": "string"},
                "decision_applied": {"type": "boolean"},
                "approval_control_completion_evidence": {"type": "boolean"},
                "run_phase": {"type": "string"},
                "run_governance": {"type": "string"},
                "run_acceptance": {"type": "string"},
                "run_resolution": {"type": "string"},
                "continuation_status": {"type": "string"},
                "completion_evidence": {"type": "boolean"},
                "continuation_requires_approval": {"type": "boolean"},
                "continuation_pending_approval_is_distinct": {"type": "boolean"},
                "goal_id": {"type": "string"},
                "loop_run_id": {"type": "string"},
                "loop_terminal_state": {"type": "string"},
                "result_summary": {"type": "string"},
                "pending_approval": {"type": "object"},
                "current_approval": {"type": "object"},
                "continuation_error": {"type": "string"},
                "continuation_result": {"type": "object"},
                "continuation_checker_results": {
                    "type": "array",
                    "items": {"type": "object"},
                },
                "connector_delivery": {"type": "object"},
                "reason": {"type": "string"},
                "approval_resolution": {"type": "object"},
                "selection": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
        approval_policy="control_plane",
    ),
    ToolSpec(
        name="session.request_elevation",
        capability_class="session",
        risk_class="medium",
        sensitive_contexts=("approval_control", "session_permission"),
        confirmation_required=False,
        risk_reason_code="capability_safeguard_session_elevation",
        execution_contexts=("turn",),
        description="""Request a temporary elevation of the session's operating permission ceiling (e.g., from 'read' to 'write').""",
        input_schema={
            "type": "object",
            "properties": {
                "target_permission": {"type": "string", "enum": ["prepare", "write", "execute"]},
                "reason": {"type": "string"},
            },
            "required": ["target_permission"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "phase": {"type": "string"},
                "governance": {"type": "string"},
                "acceptance": {"type": "string"},
                "resolution": {"type": "string"},
                "target_permission": {"type": "string"},
                "reason": {"type": "string"},
                "approval": {
                    "type": "object",
                    "properties": {
                        "action": {"type": "string"},
                        "code": {"type": "string"},
                        "expires_at": {"type": "number"},
                    },
                },
                "run_id": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="read",
        source="action",
        approval_policy="control_plane",
    ),
    ToolSpec(
        name="session.create",
        capability_class="session",
        execution_contexts=("api",),
        description="""Create a conversation session, optionally binding an alias.""",
        input_schema={"type": "object", "properties": {"alias": {"type": "string"}}},
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "session_id": {"type": "string"},
                "alias": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        approval_policy="explicit_control",
        source="action",
    ),
    ToolSpec(
        name="identity.state",
        capability_class="identity",
        execution_contexts=("turn", API_CONTEXT),
        description=(
            "Read the current actor's explicit cross-surface identity links. "
            "Returns opaque identities and alias fingerprints, never raw channel IDs."
        ),
        input_schema={"type": "object", "properties": {}},
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "linked": {"type": "boolean"},
                "identity_id": {"type": "string"},
                "aliases": {"type": "array", "items": {"type": "object"}},
            },
        },
        facts_only=True,
        mutates=False,
        permission="read",
        source="action",
    ),
    ToolSpec(
        name="identity.link",
        capability_class="identity",
        execution_contexts=("turn", API_CONTEXT),
        description=(
            "Request or confirm a two-channel identity link, or unlink the current "
            "channel. The target channel must present the one-time verification code."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "operation": {
                    "type": "string",
                    "enum": ["request", "confirm", "unlink"],
                },
                "other_source": {"type": "string"},
                "other_peer_id": {"type": "string"},
                "other_sender_id": {"type": "string"},
                "verification_code": {"type": "string"},
                "reason": {"type": "string"},
            },
            "required": ["operation", "reason"],
            "allOf": [
                {
                    "if": {"properties": {"operation": {"const": "request"}}},
                    "then": {
                        "required": [
                            "other_source",
                            "other_peer_id",
                            "other_sender_id",
                        ]
                    },
                },
                {
                    "if": {"properties": {"operation": {"const": "confirm"}}},
                    "then": {"required": ["verification_code"]},
                },
            ],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "identity_id": {"type": "string"},
                "aliases": {"type": "array", "items": {"type": "object"}},
                "migrated_memory_count": {"type": "integer"},
                "request_id": {"type": "string"},
                "verification_code": {"type": "string"},
                "expires_at": {"type": "number"},
                "unlinked": {"type": "boolean"},
                "reason": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="memory.add",
        capability_class="memory",
        risk_class="medium",
        sensitive_contexts=("memory", "local_state"),
        confirmation_required=False,
        risk_reason_code="scoped_memory_mutation",
        execution_contexts=("turn", API_CONTEXT),
        description=(
            "Add or revoke one typed durable memory item through the governed "
            "capability boundary. Omitted scope defaults to the current actor; "
            "explicit scope cannot exceed the caller's actor, session, or workspace "
            "envelope. Global writes are reserved for the trusted local control surface."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "operation": {"type": "string", "enum": ["add", "revoke"]},
                "memory_id": {"type": "string"},
                "type": {"type": "string"},
                "content": {"type": "string"},
                "scope": {
                    "type": "string",
                    "description": (
                        "Optional caller-relative scope kind: global, actor, session, "
                        "or workspace. Omission selects actor scope."
                    ),
                },
                "source": {"type": "string"},
                "status": {"type": "string"},
                "confidence": {"type": "number"},
                "reason": {"type": "string"},
                "provenance": {"type": "string"},
                "metadata": {"type": "object"},
            },
            "required": ["reason", "provenance"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "item": {"type": "object"},
                "memory_id": {"type": "string"},
                "reason": {"type": "string"},
                "provenance": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="personal.query",
        capability_class="personal_resource",
        execution_contexts=("turn", API_CONTEXT),
        description=(
            "Query the current person's calendar events, reminders, contacts, mail "
            "drafts, and attention policies. Mail records are drafts only; this "
            "capability never claims external delivery."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "resource_id": {"type": "string"},
                "kinds": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "calendar_event",
                            "reminder",
                            "contact",
                            "mail_draft",
                            "attention_policy",
                        ],
                    },
                },
                "query": {"type": "string"},
                "include_deleted": {"type": "boolean"},
                "limit": {"type": "integer", "minimum": 1, "maximum": 200},
            },
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "resources": {"type": "array", "items": {"type": "object"}},
                "count": {"type": "integer"},
                "supported_kinds": {"type": "array", "items": {"type": "string"}},
                "mail_delivery_supported": {"type": "boolean"},
            },
            "required": [
                "entity_type",
                "entity_id",
                "state_transition",
                "turn_scope",
                "resources",
                "count",
            ],
        },
        facts_only=True,
        mutates=False,
        permission="read",
        source="action",
    ),
    ToolSpec(
        name="personal.update",
        capability_class="personal_resource",
        execution_contexts=("turn", API_CONTEXT),
        description=(
            "Create, update, complete, or soft-delete one local personal resource. "
            "Updates require an expected_version and return authoritative read-back "
            "facts. mail_draft never sends mail."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "operation": {
                    "type": "string",
                    "enum": ["create", "update", "complete", "delete"],
                },
                "kind": {
                    "type": "string",
                    "enum": [
                        "calendar_event",
                        "reminder",
                        "contact",
                        "mail_draft",
                        "attention_policy",
                    ],
                },
                "resource_id": {"type": "string"},
                "expected_version": {"type": "integer", "minimum": 1},
                "data": {"type": "object"},
            },
            "required": ["operation"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "resource": {"type": "object"},
                "verified_after": {"type": "object"},
                "mail_delivery_supported": {"type": "boolean"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        risk_class="medium",
        sensitive_contexts=("personal_data", "local_state"),
        confirmation_required=True,
        risk_reason_code="personal_resource_mutation_requires_approval",
    ),
    ToolSpec(
        name="system.metrics",
        capability_class="observability",
        execution_contexts=("turn", API_CONTEXT),
        description=(
            "Read event-derived runtime metrics, SLO status, and structured backlog "
            "diagnostics without exposing conversation content."
        ),
        input_schema={"type": "object", "properties": {}},
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "generated_at": {"type": "number"},
                "overall_status": {"type": "string"},
                "metrics": {"type": "array", "items": {"type": "object"}},
                "slos": {"type": "array", "items": {"type": "object"}},
                "diagnostics": {"type": "object"},
            },
            "required": [
                "entity_type",
                "entity_id",
                "state_transition",
                "turn_scope",
                "generated_at",
                "overall_status",
                "metrics",
                "slos",
                "diagnostics",
            ],
        },
        facts_only=True,
        mutates=False,
        permission="read",
        source="action",
    ),
    ToolSpec(
        name="trace.evaluate",
        capability_class="trace",
        risk_class="medium",
        sensitive_contexts=("trace", "derived_state"),
        confirmation_required=False,
        risk_reason_code="trace_evaluation_record",
        execution_contexts=("api",),
        description="""Evaluate one trace and persist the trace evaluation record.""",
        input_schema={
            "type": "object",
            "properties": {"trace_id": {"type": "string"}},
            "required": ["trace_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "evaluation": {"type": "object"},
                "trace_id": {"type": "string"},
                "evaluation_id": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="trace.delete",
        capability_class="trace",
        execution_contexts=(API_CONTEXT,),
        description=(
            "Delete one trace or the complete trace collection and return verified read-back facts."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "trace_id": {"type": "string"},
                "all": {"type": "boolean"},
            },
            "oneOf": [
                {"required": ["trace_id"]},
                {
                    "properties": {"all": {"const": True}},
                    "required": ["all"],
                },
            ],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "scope": {"type": "string"},
                "verified_after": {"type": "object"},
                "trace_id": {"type": "string"},
                "trace_count": {"type": "integer"},
                "existed": {"type": "boolean"},
                "deleted_event_count": {"type": "integer"},
                "deleted_evaluation_count": {"type": "integer"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        approval_policy="explicit_control",
        source="action",
    ),
    ToolSpec(
        name="evolution.propose",
        capability_class="evolution",
        execution_contexts=("turn", API_CONTEXT),
        description="""Create a reviewable evolution proposal through the capability boundary.""",
        input_schema={
            "type": "object",
            "properties": {
                "target_type": {"type": "string"},
                "target_id": {"type": "string"},
                "reason": {"type": "string"},
                "expected_benefit": {"type": "string"},
                "risk": {"type": "string"},
                "before": {"type": "string"},
                "after": {"type": "string"},
                "rollback_plan": {"type": "string"},
                "required_approval_level": {"type": "string"},
                "evidence": {"type": "string"},
                "source_run_id": {"type": "string"},
                "eval_cases": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                },
            },
            "required": ["target_type", "target_id", "reason", "eval_cases"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "proposal_id": {"type": "string"},
                "proposal": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
    ),
    ToolSpec(
        name="evolution.experiment",
        capability_class="evolution",
        execution_contexts=("turn", API_CONTEXT),
        description=(
            "Run and persist declared evaluation cases against one proposal without "
            "applying its side effect. A failed experiment cannot authorize apply."
        ),
        input_schema={
            "type": "object",
            "properties": {"proposal_id": {"type": "string"}},
            "required": ["proposal_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "proposal_id": {"type": "string"},
                "experiment": {"type": "object"},
            },
            "required": [
                "entity_type",
                "entity_id",
                "state_transition",
                "turn_scope",
                "proposal_id",
                "experiment",
            ],
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
    ),
    ToolSpec(
        name="evolution.state",
        capability_class="evolution",
        execution_contexts=("turn", API_CONTEXT),
        description=(
            "Read a proposal, its latest persisted experiment, and activation observation state."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "proposal_id": {"type": "string"},
                "event_id": {"type": "string"},
            },
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "proposal": {"type": "object"},
                "experiment": {"type": "object"},
                "activation": {"type": "object"},
                "active_observations": {"type": "array", "items": {"type": "object"}},
            },
            "required": [
                "entity_type",
                "entity_id",
                "state_transition",
                "turn_scope",
                "proposal",
                "experiment",
                "activation",
                "active_observations",
            ],
        },
        facts_only=True,
        mutates=False,
        permission="read",
        source="action",
    ),
    ToolSpec(
        name="evolution.observe",
        capability_class="evolution",
        execution_contexts=(API_CONTEXT,),
        description=(
            "Record post-activation canary outcomes. Regressions beyond the "
            "approved threshold trigger the proposal's persisted rollback."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "event_id": {"type": "string"},
                "successes": {"type": "integer", "minimum": 0},
                "errors": {"type": "integer", "minimum": 0},
                "evidence": {"type": "object"},
            },
            "required": ["event_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "event_id": {"type": "string"},
                "activation": {"type": "object"},
            },
            "required": [
                "entity_type",
                "entity_id",
                "state_transition",
                "turn_scope",
                "event_id",
                "activation",
            ],
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="evolution.record_evaluation",
        capability_class="evolution",
        execution_contexts=("api",),
        description="""Attach evaluation evidence to an evolution proposal.""",
        input_schema={
            "type": "object",
            "properties": {
                "proposal_id": {"type": "string"},
                "evaluation_result": {"type": "string"},
                "evaluation_evidence": {"type": "string"},
                "approval_id": {
                    "type": "string",
                    "description": "Required when evaluation_result is approved; must reference an approved evolution.apply approval for the same proposal_id.",
                },
            },
            "required": ["proposal_id", "evaluation_result"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "proposal_id": {"type": "string"},
                "proposal": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="evolution.apply",
        capability_class="evolution",
        execution_contexts=("api",),
        description="""Apply an approved evolution proposal.""",
        input_schema={
            "type": "object",
            "properties": {"proposal_id": {"type": "string"}},
            "required": ["proposal_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "event": {"type": "object"},
                "proposal_id": {"type": "string"},
                "event_id": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
    ToolSpec(
        name="evolution.rollback",
        capability_class="evolution",
        execution_contexts=("api",),
        description="""Roll back a reversible evolution event.""",
        input_schema={
            "type": "object",
            "properties": {"event_id": {"type": "string"}},
            "required": ["event_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "event": {"type": "object"},
                "event_id": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
    ),
]
