from ..tools import ToolSpec

ACTION_SPECS = [
    ToolSpec(
        name="final.answer",
        capability_class="conversation",
        execution_contexts=("turn", "actuator", "react", "workflow_step"),
        description="""Return a final user-facing message.""",
        input_schema={
            "type": "object",
            "properties": {"message": {"type": "string"}},
            "required": ["message"],
        },
        output_schema={"type": "object", "properties": {"message": {"type": "string"}}},
        facts_only=True,
        mutates=False,
        permission="read",
        source="action",
        routing_hints=[
            "Route ordinary conversation, advice, and unstructured output to conversational capabilities.",
            "When factual accuracy matters, prefer using a read/search capability first. But if the answer is conversational or the model has sufficient context from prior observations, answering directly is fine.",
            "Do not use final.answer to answer current tool, skill, service, provider, task, workflow, or connector inventory/status questions when a declared read capability can return current facts first.",
        ],
    ),
    ToolSpec(
        name="ask.user",
        capability_class="conversation",
        execution_contexts=("turn", "actuator", "workflow_step"),
        description="""Ask the user a question to clarify requirements or present multiple choices for a decision, suitable for human-in-the-loop workflows.""",
        input_schema={
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "description": "The question or context to present to the user.",
                },
                "options": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Optional list of explicit choices for the user to pick from.",
                },
            },
            "required": ["message"],
        },
        output_schema={"type": "object", "properties": {"message": {"type": "string"}}},
        facts_only=True,
        mutates=False,
        permission="read",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="delegate.spawn",
        capability_class="delegation",
        execution_contexts=("turn", "workflow_step"),
        description="""Create a narrowly-scoped delegation run for a specific, verified step. Must only be used after gathering sufficient local facts via foreground tools.""",
        input_schema={
            "type": "object",
            "properties": {
                "objective": {"type": "string", "description": "The main goal of this delegation."},
                "context": {
                    "type": "string",
                    "description": "Relevant background information, gathered facts, and constraints.",
                },
                "plan": {
                    "type": "string",
                    "description": "A high-level step-by-step plan for the subagent to follow.",
                },
                "success_criteria": {
                    "type": "string",
                    "description": "How to verify that the delegation succeeded.",
                },
            },
            "required": ["objective", "context", "plan", "success_criteria"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "status": {"type": "string"},
                "goal_id": {"type": "string"},
                "workspace": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
        routing_hints=[
            "FACT-FIRST: Never spawn a delegation blindly. Always use file.read, shell.run, or system.info to confirm the environment, locate files, and gather facts BEFORE creating a delegation.",
            "GATED DELEGATION: Break complex requests into smaller, single-purpose delegations. Do not create massive 'do everything' tasks.",
            "LOCAL-FIRST: For simple/safe queries like checking a status, reading a file, or running 'grep'/'find', use shell.run directly in the foreground. Avoid the overhead of delegate.spawn for read-only lookups.",
        ],
    ),
    ToolSpec(
        name="delegate.prepare",
        capability_class="delegation",
        execution_contexts=("turn", "workflow_step"),
        description="""Prepare an existing delegation run and return preparation facts.""",
        input_schema={
            "type": "object",
            "properties": {"run_id": {"type": "string"}},
            "required": ["run_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "status": {"type": "string"},
                "plan_summary": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="approval.request",
        capability_class="approval",
        execution_contexts=("turn", "workflow_step"),
        description="""Create an approval request for a delegation run.""",
        input_schema={
            "type": "object",
            "properties": {"run_id": {"type": "string"}},
            "required": ["run_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "status": {"type": "string"},
                "approval": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="delegate.run",
        capability_class="delegation",
        execution_contexts=("turn", "workflow_step"),
        description="""Queue a delegation run that has an execution grant.""",
        input_schema={
            "type": "object",
            "properties": {"run_id": {"type": "string"}},
            "required": ["run_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "status": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="watch.create",
        capability_class="watch",
        execution_contexts=("turn", "workflow_step"),
        description="""Create a scheduled watch record.""",
        input_schema={
            "type": "object",
            "properties": {
                "prompt": {"type": "string"},
                "cron": {"type": "string"},
                "run_at": {"type": "number"},
                "run_at_text": {"type": "string"},
                "kind": {"type": "string", "enum": ["once", "recurring"]},
            },
            "required": ["prompt"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "watch_id": {"type": "string"},
                "cron": {"type": "string"},
                "kind": {"type": "string"},
                "prompt": {"type": "string"},
                "next_run_at": {"type": "number"},
                "next_run_text": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
        routing_hints=[
            "Use watch.create only when the user supplied a sufficiently specific recurring schedule or one-shot time. If the timing is only a broad part of day or otherwise ambiguous, ask.user for clarification instead of inventing a default time.",
            "For one-shot reminders or pushes with a natural-language time, set kind=once and pass run_at_text from the user's wording. Do not call shell.run just to compute the current timestamp.",
        ],
    ),
    ToolSpec(
        name="delegate.delete",
        capability_class="delegation",
        execution_contexts=("turn", "workflow_step"),
        description="""Delete delegation run records by id or by supported cleanup filters. Supports deleting any run (even if not failed) but requires user approval.""",
        input_schema={
            "type": "object",
            "properties": {
                "run_id": {"type": "string"},
                "status": {"type": "string"},
                "source": {"type": "string"},
                "kind": {"type": "string"},
                "limit": {"type": "integer"},
            },
            "required": [],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "deleted": {"type": "boolean"},
                "deleted_count": {"type": "integer"},
                "remaining_count": {"type": "integer"},
                "cleanup_complete": {"type": "boolean"},
                "deleted_runs": {"type": "array", "items": {"type": "object"}},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="watch.delete",
        capability_class="watch.delete",
        execution_contexts=("turn", "workflow_step"),
        description="""Permanently delete a watch or task (recurring or one-time) by watch id. Requires user approval.""",
        input_schema={
            "type": "object",
            "properties": {"watch_id": {"type": "string"}},
            "required": ["watch_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "watch_id": {"type": "string"},
                "deleted": {"type": "boolean"},
                "cron": {"type": "string"},
                "prompt": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="approval.resolve",
        capability_class="approval",
        execution_contexts=("turn", "workflow_step"),
        description="""Resolve a pending approval by explicit code, current run id, or an explicit visible approval selection.""",
        input_schema={
            "type": "object",
            "properties": {
                "decision": {"type": "string", "enum": ["approve", "reject"]},
                "code": {"type": "string"},
                "run_id": {"type": "string"},
                "selection": {
                    "type": "string",
                    "enum": ["explicit_code", "current_run", "latest_visible_batch", "all_visible"],
                },
            },
            "required": ["decision"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "approval_status": {"type": "string"},
                "run_status": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[
            "For approval resolution, preserve explicit approval codes as arguments rather than consuming them. DO NOT attempt to resolve an approval (e.g. calling approval.resolve) unless the user explicitly provides an approval code or explicitly asks to approve/reject.",
            "For phrases like approve all, do not invent codes. Use selection=latest_visible_batch only when the user explicitly asks to approve/reject all visible/current approvals.",
        ],
    ),
    ToolSpec(
        name="delegate.retry",
        capability_class="delegation",
        execution_contexts=("turn", "workflow_step"),
        description="""Execute one follow-up attempt for a delegation run.""",
        input_schema={
            "type": "object",
            "properties": {"run_id": {"type": "string"}, "follow_up_prompt": {"type": "string"}},
            "required": ["run_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "run_id": {"type": "string"},
                "status": {"type": "string"},
                "result_summary": {"type": "string"},
                "error": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="workflow.propose",
        capability_class="workflow",
        execution_contexts=("turn",),
        description="""Propose a governed dynamic workflow with declared subagent steps and verification strategy.""",
        input_schema={
            "type": "object",
            "properties": {
                "objective": {"type": "string"},
                "permission_ceiling": {"type": "string"},
                "max_concurrency": {"type": "integer"},
                "total_subagent_limit": {"type": "integer"},
                "risk_class": {"type": "string"},
                "estimated_cost": {"type": "string"},
                "stop_condition": {"type": "string"},
                "verification_strategy": {"type": "string"},
                "plan": {"type": "object"},
                "steps": {"type": "array", "items": {"type": "object"}},
            },
            "required": ["objective"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "workflow_id": {"type": "string"},
                "status": {"type": "string"},
                "confirmation_required": {"type": "boolean"},
                "permission_ceiling": {"type": "string"},
                "max_concurrency": {"type": "integer"},
                "total_subagent_limit": {"type": "integer"},
                "step_count": {"type": "integer"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
        routing_hints=[
            "For workflow.propose, declare plan.goal_type as planning only when the workflow is meant to produce planning evidence without external capability execution; execution goals need declared tool_calls."
        ],
    ),
    ToolSpec(
        name="workflow.approve",
        capability_class="workflow",
        execution_contexts=("turn",),
        description="""Approve or reject a proposed dynamic workflow before it can run.""",
        input_schema={
            "type": "object",
            "properties": {
                "workflow_id": {"type": "string"},
                "decision": {"type": "string", "enum": ["approve", "reject"]},
            },
            "required": ["workflow_id", "decision"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "workflow_id": {"type": "string"},
                "status": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="workflow.run",
        capability_class="workflow",
        execution_contexts=("turn",),
        description="""Run the next bounded batch of an approved dynamic workflow through declared capabilities.""",
        input_schema={
            "type": "object",
            "properties": {"workflow_id": {"type": "string"}},
            "required": ["workflow_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "workflow_id": {"type": "string"},
                "status": {"type": "string"},
                "completed_count": {"type": "integer"},
                "failed_count": {"type": "integer"},
                "pending_count": {"type": "integer"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="workflow.verify",
        capability_class="workflow",
        execution_contexts=("turn",),
        description="""Run verifier checks for a completed dynamic workflow and mark it verified or blocked.""",
        input_schema={
            "type": "object",
            "properties": {"workflow_id": {"type": "string"}},
            "required": ["workflow_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "workflow_id": {"type": "string"},
                "status": {"type": "string"},
                "verifier_passed": {"type": "boolean"},
                "blocked_reason": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="workflow.resume",
        capability_class="workflow",
        execution_contexts=("turn",),
        description="""Resume an approved, running, or interrupted dynamic workflow from persisted step state.""",
        input_schema={
            "type": "object",
            "properties": {"workflow_id": {"type": "string"}},
            "required": ["workflow_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "workflow_id": {"type": "string"},
                "status": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="workflow.status",
        capability_class="workflow",
        execution_contexts=("turn",),
        description="""Inspect one dynamic workflow, including step state, evidence, and lifecycle events.""",
        input_schema={
            "type": "object",
            "properties": {"workflow_id": {"type": "string"}},
            "required": ["workflow_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "workflow": {"type": "object"},
                "steps": {"type": "array", "items": {"type": "object"}},
                "events": {"type": "array", "items": {"type": "object"}},
                "step_count": {"type": "integer"},
                "pending_count": {"type": "integer"},
                "completed_count": {"type": "integer"},
                "failed_count": {"type": "integer"},
            },
        },
        facts_only=True,
        mutates=False,
        permission="read",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="session.request_elevation",
        capability_class="session",
        execution_contexts=("turn", "workflow_step"),
        description="""Request temporary elevation of the session's permission ceiling. Elevates from current level (e.g., read) to a higher level (prepare, write, execute).""",
        input_schema={
            "type": "object",
            "properties": {
                "target_permission": {"type": "string", "enum": ["prepare", "write", "execute"]},
                "reason": {"type": "string"},
            },
            "required": ["target_permission", "reason"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "status": {"type": "string"},
                "message": {"type": "string"},
                "approval_code": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="read",
        source="action",
        routing_hints=[
            "Only use this when a capability you need is genuinely not in the tool manifest due to permission ceiling. Most tools (shell.run, file.write, web.search, etc.) should already be available at write permission level. Check the manifest first before escalating."
        ],
    ),
    ToolSpec(
        name="session.create",
        capability_class="session",
        execution_contexts=("api",),
        description="""Create a conversation session, optionally binding an alias.""",
        input_schema={"type": "object", "properties": {"alias": {"type": "string"}}},
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "session_id": {"type": "string"},
                "alias": {"type": "string"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="memory.add",
        capability_class="memory",
        execution_contexts=("api",),
        description="""Add one typed durable memory item through the capability boundary.""",
        input_schema={
            "type": "object",
            "properties": {
                "type": {"type": "string"},
                "content": {"type": "string"},
                "scope": {"type": "string"},
                "source": {"type": "string"},
                "status": {"type": "string"},
                "confidence": {"type": "number"},
                "metadata": {"type": "object"},
            },
            "required": ["type", "content"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "item": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="trace.evaluate",
        capability_class="trace",
        execution_contexts=("api",),
        description="""Evaluate one trace and persist the trace evaluation record.""",
        input_schema={
            "type": "object",
            "properties": {"trace_id": {"type": "string"}},
            "required": ["trace_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "evaluation": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="evolution.propose",
        capability_class="evolution",
        execution_contexts=("api",),
        description="""Create a reviewable evolution proposal through the capability boundary.""",
        input_schema={
            "type": "object",
            "properties": {
                "target_type": {"type": "string"},
                "target_id": {"type": "string"},
                "reason": {"type": "string"},
                "expected_benefit": {"type": "string"},
                "risk": {"type": "string"},
                "before": {"type": "string"},
                "after": {"type": "string"},
                "rollback_plan": {"type": "string"},
                "required_approval_level": {"type": "string"},
                "evidence": {"type": "string"},
                "source_run_id": {"type": "string"},
                "eval_cases": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["target_type", "target_id", "reason"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "proposal": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="prepare",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="evolution.record_evaluation",
        capability_class="evolution",
        execution_contexts=("api",),
        description="""Attach evaluation evidence to an evolution proposal.""",
        input_schema={
            "type": "object",
            "properties": {
                "proposal_id": {"type": "string"},
                "evaluation_result": {"type": "string"},
            },
            "required": ["proposal_id", "evaluation_result"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "proposal": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="evolution.apply",
        capability_class="evolution",
        execution_contexts=("api",),
        description="""Apply an approved evolution proposal.""",
        input_schema={
            "type": "object",
            "properties": {"proposal_id": {"type": "string"}},
            "required": ["proposal_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "event": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[],
    ),
    ToolSpec(
        name="evolution.rollback",
        capability_class="evolution",
        execution_contexts=("api",),
        description="""Roll back a reversible evolution event.""",
        input_schema={
            "type": "object",
            "properties": {"event_id": {"type": "string"}},
            "required": ["event_id"],
        },
        output_schema={
            "type": "object",
            "properties": {
                "entity_type": {"type": "string"},
                "entity_id": {"type": "string"},
                "state_transition": {"type": "string"},
                "turn_scope": {"type": "string"},
                "event": {"type": "object"},
            },
        },
        facts_only=True,
        mutates=True,
        permission="write",
        source="action",
        routing_hints=[],
    ),
]
