from __future__ import annotations

APPROVAL_DECISION_APPROVE = "approve"
APPROVAL_DECISION_REJECT = "reject"
APPROVAL_DECISIONS = frozenset(
    {
        APPROVAL_DECISION_APPROVE,
        APPROVAL_DECISION_REJECT,
    }
)

APPROVAL_STATUS_PENDING = "pending"
APPROVAL_STATUS_APPROVED = "approved"
APPROVAL_STATUS_REJECTED = "rejected"
APPROVAL_STATUS_EXPIRED = "expired"
