"""Workflows subsystem: domain types, persistence, and transition logic."""

from __future__ import annotations

from .domain import (
    STEP_FAILED_STATUSES,
    STEP_STATUSES,
    STEP_STATUS_BLOCKED,
    STEP_STATUS_COMPLETED,
    STEP_STATUS_FAILED,
    STEP_STATUS_PENDING,
    STEP_STATUS_RUNNING,
    STEP_TERMINAL_STATUSES,
    WORKFLOW_RUNNABLE_STATUSES,
    WORKFLOW_STATUSES,
    WORKFLOW_STATUS_APPROVED,
    WORKFLOW_STATUS_AWAITING_APPROVAL,
    WORKFLOW_STATUS_BLOCKED,
    WORKFLOW_STATUS_COMPLETED,
    WORKFLOW_STATUS_INTERRUPTED,
    WORKFLOW_STATUS_REJECTED,
    WORKFLOW_STATUS_RUNNING,
    WORKFLOW_STATUS_VERIFIED_COMPLETE,
    WORKFLOW_STORE_SCHEMA_VERSION,
    Workflow,
    WorkflowCheckResult,
    WorkflowEvent,
    WorkflowStep,
    WorkflowTransitionDecision,
    WorkflowVerificationDecision,
    workflow_batch_transition,
    workflow_can_run,
    workflow_idle_transition,
    workflow_verification_decision,
)
from .schema import (
    WORKFLOW_EVENTS_TABLE,
    WORKFLOW_STEPS_TABLE,
    WORKFLOWS_TABLE,
)
from .store import WorkflowStore, workflow_facts

__all__ = [
    "STEP_FAILED_STATUSES",
    "STEP_STATUSES",
    "STEP_STATUS_BLOCKED",
    "STEP_STATUS_COMPLETED",
    "STEP_STATUS_FAILED",
    "STEP_STATUS_PENDING",
    "STEP_STATUS_RUNNING",
    "STEP_TERMINAL_STATUSES",
    "WORKFLOW_EVENTS_TABLE",
    "WORKFLOW_RUNNABLE_STATUSES",
    "WORKFLOW_STATUSES",
    "WORKFLOW_STEPS_TABLE",
    "WORKFLOW_STATUS_APPROVED",
    "WORKFLOW_STATUS_AWAITING_APPROVAL",
    "WORKFLOW_STATUS_BLOCKED",
    "WORKFLOW_STATUS_COMPLETED",
    "WORKFLOW_STATUS_INTERRUPTED",
    "WORKFLOW_STATUS_REJECTED",
    "WORKFLOW_STATUS_RUNNING",
    "WORKFLOW_STATUS_VERIFIED_COMPLETE",
    "WORKFLOW_STORE_SCHEMA_VERSION",
    "WORKFLOWS_TABLE",
    "Workflow",
    "WorkflowCheckResult",
    "WorkflowEvent",
    "WorkflowStep",
    "WorkflowStore",
    "WorkflowTransitionDecision",
    "WorkflowVerificationDecision",
    "workflow_batch_transition",
    "workflow_can_run",
    "workflow_facts",
    "workflow_idle_transition",
    "workflow_verification_decision",
]
